// GENERATED by scripts/shots.mjs — do not edit. Run `npm run generate`.
//
// The intrinsic size of every screenshot in public/shots, keyed by the URL a page
// references it with. Read by lib/shots.ts, which is what the <img> width/height and the
// no-upscale ceiling come from.

export const SHOT_SIZES: Record<string, readonly [number, number]> = {
  "/claude-tray/shots/context-all.png": [1974, 1425],
  "/claude-tray/shots/context.png": [1974, 1425],
  "/claude-tray/shots/menu.png": [610, 336],
  "/claude-tray/shots/notify-bonus.png": [800, 400],
  "/claude-tray/shots/notify-context.png": [800, 400],
  "/claude-tray/shots/notify-extra.png": [800, 400],
  "/claude-tray/shots/notify-profile.png": [800, 314],
  "/claude-tray/shots/notify-session.png": [800, 400],
  "/claude-tray/shots/notify-surprise.png": [800, 400],
  "/claude-tray/shots/notify-weekly.png": [800, 400],
  "/claude-tray/shots/statistics-5h.png": [1300, 1368],
  "/claude-tray/shots/statistics-7d.png": [1300, 1368],
  "/claude-tray/shots/statistics-overage.png": [1300, 1368],
  "/claude-tray/shots/statistics-sessions.png": [1300, 1368],
  "/claude-tray/shots/statistics-throughput.png": [1300, 1368],
  "/claude-tray/shots/system-account.png": [1300, 846],
  "/claude-tray/shots/system.png": [1300, 846],
  "/claude-tray/shots/tooltip.png": [480, 196],
  "/claude-tray/shots/usage.png": [926, 506],
};
